### ISSUE TITLE
Cannot Read Vita NPTickets

### ISSUE THREAD

**Issue by turecross321** [LittleBigRefresh/NPTicket#4]
`Could not read ticket: System.FormatException: Expected last section to be Footer, was really 16 (16)`

**Comment by jvyden** [comment]
Oops, that's an oversight. I never implemented proper support for reading 3.0 tickets (I just assumed 2.1), so now that's coming back to bite us in the ass. For now I'd recommend projects roll back to 2.0

**Comment by jvyden** [comment]
Fixed in v3.1.0. Verification is untested.
